Updated by @hohno_at_kuimc on hohno-SP6-2019H

diff --git a/lsgithub b/lsgithub
--- a/lsgithub
+++ b/lsgithub
@@ -1,4 +1,4 @@
-#! /bin/sh
+#!/bin/sh
 
 # lsgithub
 
@@ -23,6 +23,7 @@
 # ----------------------------------------------------------
 
 # See also:
+# https://docs.github.com/en/rest/repos/repos
 # https://developer.github.com/v3/repos/#list-user-repositories
 # https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/
 # https://docs.github.com/en/rest/overview/resources-in-the-rest-api
@@ -33,17 +34,17 @@
 
 # ----------------------------------------------------------
 
-error_exit () {
-    echo "Error: $1"
-    exit $2
-}
-
-# ----------------------------------------------------------
-
 usage () {
     echo "usage: $(basename $0) [-l] [-c] [-t] [-r] [--public] [--private] [--all|--everybody] [--owner] [--others] [--ssh|--https] [--clone] [-q|--quiet]"
     echo "usage: $(basename $0) [-h|--help]"
     exit $1
+}
+
+# ----------------------------------------------------------
+
+error_exit () {
+    echo "Error: $1"
+    exit $2
 }
 
 # ----------------------------------------------------------
@@ -66,6 +67,7 @@ touch "$TMPFILE"
 # GITHUB_USER="...."
 # ACCESS_TOKEN="........"
 #
+
 if [ -r "$SECRET_FILE" ] ; then
    eval $(cat "$SECRET_FILE" \
         | expand \
@@ -88,7 +90,7 @@ fi
 
 # echo "[$GITHUB_USER]($afo)"
 # echo "[$ACCESS_TOKEN]"
-# exit
+# exit 99
 
 # ----------------------------------------------------------
 
@@ -122,7 +124,7 @@ if [ "x$?" != "x0" ]; then
 fi
 
 # echo "[$OPTS]"
-# exit
+# exit 99
 
 eval set -- "$OPTS"
 
@@ -223,13 +225,12 @@ elif [ "x$STYLE2" = "x1" ] ; then
 fi
 
 # echo "[$CMD3]"
-# exit 9
+# exit 99
 
 CMD1="$CMD1 $SORTOPT"
 
 # echo curl -s "https://api.github.com/user/repos?access_token=${ACCESS_TOKEN}&type=${REPO_TYPE}&per_page=100" \
 # curl -H "Authorization: token ${ACCESS_TOKEN}" "https://api.github.com/user/repos?&type=${REPO_TYPE}&per_page=100" 2> /dev/null \
-
 
 x=0
 while [ 1 ]; do
@@ -261,11 +262,3 @@ done \
 # echo ""
 
 exit $?
-
-
-
-# | wc 
-
-exit
-#    | jq '.[] | select(.owner.login '${JQ_OP}' "'${GITHUB_USER}'") |.created_at, .updated_at, .name' \
-
